spring:
  application:
    name: Spring Boot Starter E-mail
server:
  port: 8080
debug: true
email:
  host: smtp.gmail.com
  port: 587
  username: your_username
  password: your_password
  debug: true

